namespace IlRepl.Tests.Shared;

/// <summary>
/// Supplies matching control-flow reproductions for CoreCLR, ILVerification, and browser Mono.
/// </summary>
public static class ControlFlowExamples
{
    /// <summary>
    /// The source cases; accepted methods return 42 when called with argument 1.
    /// </summary>
    public static IReadOnlyList<ControlFlowExample> All { get; } =
    [
        new("Diamond", ["ldarg.0", "brtrue OTHER", "ldc.i4.s 41", "br DONE", "OTHER: ldc.i4.s 42", "DONE: ret"], true),
        new("Loop", ["AGAIN: ldarg.0", "brfalse DONE", "ldarg.0", "ldc.i4.1", "sub", "starg.s n", "br AGAIN",
            "DONE: ldc.i4.s 42", "ret"], true),
        new("Switch", ["ldarg.0", "switch (ZERO, ONE)", "ldc.i4.0", "ret", "ZERO: ldc.i4.1", "ret",
            "ONE: ldc.i4.s 42", "ret"], true),
        new("DeadCode", ["br DONE", "pop", "DONE: ldc.i4.s 42", "ret"], true),
        new("MixedFloats", ["ldarg.0", "brtrue OTHER", "ldc.r4 1.0", "br DONE", "OTHER: ldc.r8 2.0", "DONE: pop",
            "ldc.i4.s 42", "ret"], true),
        new("Catch", [".locals init (int32 result)", ".try {", "ldnull", "throw", "} catch [System.Runtime]System.Exception {",
            "pop", "ldc.i4.s 42", "stloc result", "leave DONE", "}", "DONE: ldloc result", "ret"], true),
        new("Finally", [".locals init (int32 result)", ".try {", "leave DONE", "} finally {", "ldc.i4.s 42", "stloc result",
            "endfinally", "}", "DONE: ldloc result", "ret"], true),
        new("ManagedPointer", ["ldarga.s n", "ldc.i4.s 42", "stind.i4", "ldarg.0", "ret"], true),
        new("ArrayJoin", ["ldarg.0", "brtrue OTHER", "ldc.i4.1", "newarr string", "br DONE", "OTHER: ldc.i4.1",
            "newarr [System.Runtime]System.Exception", "DONE: ldlen", "pop", "ldc.i4.s 42", "ret"], true),
        new("StackAllocation", ["ldc.i4.4", "conv.u", "localloc", "pop", "ldc.i4.s 42", "ret"], true,
            Unverifiable: true, Verification: "Unverifiable"),
        new("WrongDepth", ["ldarg.0", "brtrue DONE", "ldc.i4.1", "DONE: pop", "ldc.i4.s 42", "ret"], false,
            "incompatible stacks", Verification: "PathStackDepth"),
        new("WrongType", ["ldarg.0", "brtrue OTHER", "ldc.i4.1", "br DONE", "OTHER: ldstr \"s\"", "DONE: pop",
            "ldc.i4.s 42", "ret"], false, "incompatible stacks", Verification: "PathStackUnexpected"),
        new("Underflow", ["pop", "ldc.i4.s 42", "ret"], false, "stack underflow", Verification: "StackUnderflow"),
        new("WrongReturn", ["ldstr \"s\"", "ret"], false, "ret needs int32", Verification: "StackUnexpected"),
        new("BackwardStack", ["br LATER", "EARLIER: pop", "ldc.i4.s 42", "ret", "LATER: ldc.i4.1", "br EARLIER"], false,
            "backward branch", Verification: "BackwardBranch"),
        new("NonemptyTry", ["ldc.i4.1", ".try {", "pop", "leave DONE", "} finally {", "endfinally", "}",
            "DONE: ldc.i4.s 42", "ret"], false, "empty stack", Verification: "TryNonEmptyStack"),
        new("ReturnInTry", [".try {", "ldc.i4.s 42", "ret", "} finally {", "endfinally", "}"], false,
            "ret is not allowed", Verification: "ReturnFromTry"),
        new("BranchIntoTry", ["br INSIDE", ".try {", "INSIDE: leave DONE", "} finally {", "endfinally", "}",
            "DONE: ldc.i4.s 42", "ret"], false, "cannot enter"),
        new("WrongPrefix", ["readonly.", "nop", "ldc.i4.s 42", "ret"], false, "cannot prefix", Verification: "ReadOnly"),
        new("WrongArithmetic", ["ldstr \"s\"", "ldc.i4.1", "add", "ret"], false, "cannot combine", Verification: "ExpectedNumericType"),
        new("WrongCall", ["ldstr \"s\"", "call int32 [System.Runtime]System.Math::Abs(int32)", "ret"], false,
            "argument 1 needs int32", Verification: "StackUnexpected"),
        new("ByrefJoin", [".locals init (int32 a, string b)", "ldarg.0", "brtrue OTHER", "ldloca a", "br DONE",
            "OTHER: ldloca b", "DONE: pop", "ldc.i4.s 42", "ret"], false, "incompatible stacks", Verification: "PathStackUnexpected"),
        new("CatchFinally", [".locals init (int32 result)", ".try {", ".try {", "ldnull", "throw",
            "} catch [System.Runtime]System.Exception {", "pop", "ldc.i4.s 32", "stloc result", "leave AFTER", "}",
            "AFTER: leave DONE", "} finally {", "ldloc result", "ldc.i4.s 10", "add", "stloc result", "endfinally", "}",
            "DONE: ldloc result", "ret"], true),
        new("Fault", [".locals init (int32 result)", ".try {", ".try {", "ldnull", "throw", "} fault {",
            "ldc.i4.s 42", "stloc result", "endfinally", "}", "} catch [System.Runtime]System.Exception {", "pop",
            "leave DONE", "}", "DONE: ldloc result", "ret"], true),
        new("ReadOnlyLoad", ["ldc.i4.1", "newarr int32", "ldc.i4.0", "readonly.", "ldelema int32", "ldind.i4", "pop",
            "ldc.i4.s 42", "ret"], true),
        new("ReadOnlyWrite", ["ldc.i4.1", "newarr int32", "ldc.i4.0", "readonly.", "ldelema int32", "ldc.i4.s 42",
            "stind.i4", "ldc.i4.s 42", "ret"], true, Unverifiable: true, Verification: "ReadOnlyIllegalWrite"),
        new("PointerDifference", ["ldarga.s n", "dup", "sub", "pop", "ldc.i4.s 42", "ret"], true,
            Unverifiable: true, Verification: "ExpectedNumericType"),
        new("NativeAddition", ["ldc.i4.1", "conv.i", "ldc.i4.s 41", "add", "conv.i4", "ret"], true),
        new("ObjectComparison", ["ldnull", "ldnull", "cgt.un", "pop", "ldc.i4.s 42", "ret"], true),
        new("TailCall", ["ldc.i4.s 42", "tail.", "call int32 [System.Runtime]System.Math::Abs(int32)", "ret"], true),
        new("UnalignedLoad", ["ldarga.s n", "unaligned. 1", "ldind.i4", "pop", "ldc.i4.s 42", "ret"], true),
        new("BadOverflowFloat", ["ldc.r8 1.0", "ldc.r8 2.0", "add.ovf", "pop", "ldc.i4.s 42", "ret"], false,
            "cannot combine", Verification: "ExpectedIntegerType"),
        new("BadNotFloat", ["ldc.r8 1.0", "not", "pop", "ldc.i4.s 42", "ret"], false,
            "needs a numeric value", Verification: "ExpectedIntegerType"),
        new("BadComparison", ["ldstr \"s\"", "ldc.i4.1", "ceq", "pop", "ldc.i4.s 42", "ret"], false,
            "cannot combine", Verification: "StackUnexpected"),
        new("BadShift", ["ldc.i4.1", "ldc.i8 1", "shl", "pop", "ldc.i4.s 42", "ret"], false,
            "cannot combine", Verification: "StackUnexpected"),
        new("BadThrow", ["ldc.i4.1", "throw"], false, "needs an object reference", Verification: "StackObjRef"),
        new("BadFinite", ["ldc.i4.1", "ckfinite", "pop", "ldc.i4.s 42", "ret"], false,
            "needs a floating-point value", Verification: "ExpectedFloatType"),
        new("BranchIntoPrefix", ["ldarga.s n", "br LOAD", "unaligned. 1", "LOAD: ldind.i4", "pop", "ldc.i4.s 42", "ret"], false,
            "first prefix", Verification: "BadJumpTarget"),
        new("GenericReference", [".locals init (!!T item)", "ldloc item", "ldnull",
            "call bool [System.Runtime]System.Object::ReferenceEquals(object, object)", "pop", "ldc.i4.s 42", "ret"], true,
            Unverifiable: true, Verification: "StackUnexpected", GenericParameters: "class T", GenericArguments: "string"),
        new("GenericBox", [".locals init (!!T item)", "ldloc item", "box !!T", "ldnull",
            "call bool [System.Runtime]System.Object::ReferenceEquals(object, object)", "pop", "ldc.i4.s 42", "ret"], true,
            GenericParameters: "T", GenericArguments: "int32"),
        new("GenericNeedsBox", [".locals init (!!T item)", "ldloc item", "ldnull",
            "call bool [System.Runtime]System.Object::ReferenceEquals(object, object)", "pop", "ldc.i4.s 42", "ret"], false,
            "argument 1 needs object", Verification: "StackUnexpected", GenericParameters: "T", GenericArguments: "int32"),
        new("GenericDistinct", [".locals init (!!T a, !!U b)", "ldarg.0", "brtrue OTHER", "ldloc a", "br DONE",
            "OTHER: ldloc b", "DONE: pop", "ldc.i4.s 42", "ret"], false, "incompatible stacks",
            Verification: "PathStackUnexpected", GenericParameters: "T, U", GenericArguments: "int32, string"),
        new("GenericReferenceThrow", [".locals init (!!T item)", ".try {", "ldloc item", "throw",
            "} catch [System.Runtime]System.Exception {", "pop", "leave DONE", "}", "DONE: ldc.i4.s 42", "ret"], true,
            Verification: "StackObjRef", GenericParameters: "class T", GenericArguments: "string"),
        new("GenericNeedsBoxThrow", [".locals init (!!T item)", "ldloc item", "throw"], false,
            "needs an object reference", Verification: "StackObjRef", GenericParameters: "T", GenericArguments: "int32"),
        new("Filter", [".locals init (int32 result)", ".try {", "ldnull", "throw", "} filter {", "pop", "ldc.i4.1",
            "endfilter", "} handler {", "pop", "ldc.i4.s 42", "stloc result", "leave DONE", "}", "DONE: ldloc result", "ret"], true),
        new("WrongFilterStack", [".try {", "ldnull", "throw", "} filter {", "pop", "ldnull", "endfilter", "} handler {",
            "pop", "leave DONE", "}", "DONE: ldc.i4.s 42", "ret"], false, "endfilter needs exactly one int32",
            Verification: "StackUnexpected"),
        new("ReducedPointerJoin", [".locals init (int32 a, uint32 b)", "ldarg.0", "brtrue OTHER", "ldloca a", "br DONE",
            "OTHER: ldloca b", "DONE: ldind.i4", "pop", "ldc.i4.s 42", "ret"], true, Verification: "PathStackUnexpected"),
        new("ConstrainedReceiver", ["ldarga.s n", "constrained. int32", "callvirt instance string object::ToString()", "pop",
            "ldc.i4.s 42", "ret"], true),
        new("WrongConstrainedReceiver", ["ldarga.s n", "constrained. int64", "callvirt instance string object::ToString()", "pop",
            "ldc.i4.s 42", "ret"], false, "receiver", Verification: "StackUnexpected"),
        new("EnumPointerJoin", [".locals init (valuetype [System.Runtime]System.DayOfWeek a, int32 b)", "ldarg.0", "brtrue OTHER",
            "ldloca a", "br DONE", "OTHER: ldloca b", "DONE: ldind.i4", "pop", "ldc.i4.s 42", "ret"], true,
            Verification: "PathStackUnexpected"),
        new("TransitiveBox", [".locals init (!!T item)", "ldloc item", "box !!T", "ldnull",
            "callvirt instance int32 [System.Runtime]System.IComparable::CompareTo(object)", "pop", "ldc.i4.s 42", "ret"], true,
            GenericParameters: "(!!U) T, (class [System.Runtime]System.IComparable) U", GenericArguments: "int32, int32"),
        new("IndirectCall", ["ldc.i4.s -42", "ldftn int32 [System.Runtime]System.Math::Abs(int32)", "calli int32(int32)", "ret"], true,
            Unverifiable: true, VerificationFailure: "ImportCalli not implemented"),
        new("WrongIndirectCall", ["ldnull", "ldftn int32 [System.Runtime]System.Math::Abs(int32)", "calli int32(int32)", "ret"], false,
            "argument 1 needs int32", VerificationFailure: "ImportCalli not implemented"),
        new("WrongAllocationStack", ["ldc.i4.0", "ldc.i4.4", "localloc", "pop", "pop", "ldc.i4.s 42", "ret"], false,
            "exactly one integer size", Verification: "Unverifiable,LocallocStackNotEmpty"),
        new("ArrayIndex", ["ldc.i4.1", "newarr int32", "ldc.i4.0", "ldelem.i4", "pop", "ldc.i4.s 42", "ret"], true),
        new("WrongArrayIndex", ["ldc.i4.1", "newarr int32", "ldc.r8 0.0", "ldelem.i4", "pop", "ldc.i4.s 42", "ret"], false,
            "integer index", Verification: "StackUnexpected"),
        new("WrongIndirectLoad", ["ldarga.s n", "ldind.ref", "pop", "ldc.i4.s 42", "ret"], false,
            "cannot access int32", Verification: "StackUnexpected"),
        new("DeepStack", [.. Enumerable.Repeat("ldc.i4.0", 32), .. Enumerable.Repeat("pop", 32), "ldc.i4.s 42", "ret"], true),
    ];
}
