<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>IlRepl.Docs.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <MSTestAnalysisMode>Recommended</MSTestAnalysisMode>
    <NoWarn>$(NoWarn);MSTESTEXP</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
