#!/usr/bin/env -S dotnet --
#:property TargetFramework=net10.0
#:project ../src/IlRepl.Engine/IlRepl.Engine.csproj

using System.Text;
using System.Text.Json;
using IlRepl.Protocol;
using IlRepl.Repl;

var root = new DirectoryInfo(Directory.GetCurrentDirectory());
while (root is not null && !File.Exists(Path.Join(root.FullName, "IlRepl.slnx")))
{
    root = root.Parent;
}

if (root is null)
{
    throw new InvalidOperationException("Run the generator inside the ilrepl repository.");
}

if (args.Any(argument => argument != "--check"))
{
    throw new ArgumentException("usage: Generate-BootstrapCatalog.cs [--check]");
}

var snapshot = new HostHello(Completer.Catalog, CilVocabularyBuilder.Vocabulary, SessionStatus.Initial);
var json = JsonSerializer.Serialize(snapshot, ProtocolJsonContext.Default.HostHello);
var content = Render(json).ReplaceLineEndings("\n");
var output = Path.Join(root.FullName, "src", "IlRepl.Protocol", "BootstrapCatalog.Generated.cs");
if (args.Contains("--check", StringComparer.Ordinal))
{
    if (!File.Exists(output) || File.ReadAllText(output).ReplaceLineEndings("\n") != content)
    {
        Console.Error.WriteLine("The bootstrap catalog is stale. Run scripts/Generate-BootstrapCatalog.cs to update it.");
        return 1;
    }

    Console.WriteLine("The bootstrap catalog matches the engine tables.");
}
else
{
    File.WriteAllText(output, content, new UTF8Encoding(false));
    Console.WriteLine("Wrote " + output);
}

return 0;

// Writes the snapshot as a C# constant, in pieces short enough to stay under the line limit.
static string Render(string json)
{
    var text = new StringBuilder("// <auto-generated />\nnamespace IlRepl.Protocol;\n\n");
    text.AppendLine("/// <summary>");
    text.AppendLine("/// Contains the generated bootstrap snapshot checked against the real engine by the catalog parity test.");
    text.AppendLine("/// </summary>");
    text.AppendLine("public static partial class BootstrapCatalog");
    text.AppendLine("{");
    var pieces = new List<string>();
    for (var offset = 0; offset < json.Length; offset += 48)
    {
        var piece = json.Substring(offset, Math.Min(48, json.Length - offset));
        pieces.Add("\"" + piece.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal) + "\"");
    }

    var groups = pieces.Chunk(32).ToArray();
    text.AppendLine("    private const string Data =");
    for (var index = 0; index < groups.Length; index++)
    {
        text.Append("        Part").Append(index).AppendLine(index == groups.Length - 1 ? ";" : " +");
    }

    for (var index = 0; index < groups.Length; index++)
    {
        text.AppendLine();
        text.Append("    private const string Part").Append(index).AppendLine(" =");
        var group = groups[index];
        for (var piece = 0; piece < group.Length; piece++)
        {
            text.Append("        ").Append(group[piece]).AppendLine(piece == group.Length - 1 ? ";" : " +");
        }
    }

    text.AppendLine("}");
    return text.ToString();
}
